### ISSUE TITLE
Support @steal in slim build

### ISSUE THREAD

**Issue by imaustink** [stealjs/stealjs#77]
```
Potentially unhandled rejection [1] Error: Cannot create slim build. "@steal" module is not supported
    at isAtSteal (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/slim/checks/steal.js:32:9)
    at Array.forEach (<anonymous>)
    at /Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/slim/checks/steal.js:21:21
    at Array.forEach (<anonymous>)
    at module.exports (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/slim/checks/steal.js:10:14)
    at checkSupport (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/stream/check_slim_support.js:20:2)
    at DestroyableTransform._transform (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/stream/check_slim_support.js:10:15)
    at DestroyableTransform.Transform._read (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/readable-stream/lib/_stream_writable.js:406:64)
```

This is preventing Bitcentive from taking advantage of the slim build, as many of its dependencies, for example,  `steal-socket.io`, use `@steal`.

**Comment by imaustink** [comment]
cc @matthewp @m-mujica

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-tools #849](https://github.com/stealjs/steal-tools/issues/849) via [**ZenHub**](https://www.zenhub.com/)
